# Sample values for an M10 instance
# of Atlas running in AWS called
# sample-dataservice

name: sample-dataservice
user: "JXPIDQEA"
publicApiKey: "697c6a30-99a4-4b85-8036-4ef56f7eabf7"
clusterType: Standalone
orgId: "599eeea79f78f769464d41a1"
version: "4.0.2"
## TODO: Add in like "small" resource requests
apikey:
  publicKey: krnruxbn
  privateKey: e488c20b-56f2-43f4-b9e4-746c9fdeca97
